wandb_version: 1

N_AGENTS:
  desc: null
  value: 8
N_ACTIONS:
  desc: null
  value: 5
EPISODE_LEN:
  desc: null
  value: 256
FOV_SIZE:
  desc: null
  value: 3
WORLD_SIZE:
  desc: null
  value:
  - 10
  - 40
OBSTACLE_PROB:
  desc: null
  value:
  - 0.0
  - 0.5
ACTION_COST:
  desc: null
  value: -0.3
IDLE_COST:
  desc: null
  value: -0.3
GOAL_REWARD:
  desc: null
  value: 0.0
COLLISION_COST:
  desc: null
  value: -2
BLOCKING_COST:
  desc: null
  value: -1
lr:
  desc: null
  value: 1.0e-05
GAMMA:
  desc: null
  value: 0.95
LAM:
  desc: null
  value: 0.95
CLIPRANGE:
  desc: null
  value: 0.2
MAX_GRAD_NORM:
  desc: null
  value: 10
ENTROPY_COEF:
  desc: null
  value: 0.01
IN_VALUE_COEF:
  desc: null
  value: 0.08
EX_VALUE_COEF:
  desc: null
  value: 0.08
POLICY_COEF:
  desc: null
  value: 10
VALID_COEF:
  desc: null
  value: 0.5
BLOCK_COEF:
  desc: null
  value: 0.5
N_EPOCHS:
  desc: null
  value: 10
N_ENVS:
  desc: null
  value: 16
N_MAX_STEPS:
  desc: null
  value: 30000000.0
N_STEPS:
  desc: null
  value: 1024
MINIBATCH_SIZE:
  desc: null
  value: 1024
DEMONSTRATION_PROB:
  desc: null
  value: 0.1
NET_SIZE:
  desc: null
  value: 512
NUM_CHANNEL:
  desc: null
  value: 8
GOAL_REPR_SIZE:
  desc: null
  value: 12
VECTOR_LEN:
  desc: null
  value: 7
N_POSITION:
  desc: null
  value: 1024
D_MODEL:
  desc: null
  value: 512
D_HIDDEN:
  desc: null
  value: 1024
N_LAYERS:
  desc: null
  value: 1
N_HEAD:
  desc: null
  value: 8
D_K:
  desc: null
  value: 32
D_V:
  desc: null
  value: 32
DIST_FACTOR:
  desc: null
  value: 0.1
K:
  desc: null
  value: 3
CAPACITY:
  desc: null
  value: 80
ADD_THRESHOLD:
  desc: null
  value: 3
N_ADD_INTRINSIC:
  desc: null
  value: 1000000.0
SURROGATE1:
  desc: null
  value: 0.2
SURROGATE2:
  desc: null
  value: 1
SEED:
  desc: null
  value: 1234
USE_GPU_LOCAL:
  desc: null
  value: false
USE_GPU_GLOBAL:
  desc: null
  value: true
NUM_GPU:
  desc: null
  value: 1
RETRAIN:
  desc: null
  value: false
WANDB:
  desc: null
  value: true
TENSORBOARD:
  desc: null
  value: true
TXT_WRITER:
  desc: null
  value: true
ENTITY:
  desc: null
  value: yutong
TIME:
  desc: null
  value: 07-03-240057
EXPERIMENT_PROJECT:
  desc: null
  value: MAPF
EXPERIMENT_NAME:
  desc: null
  value: SCRIMP
EXPERIMENT_NOTE:
  desc: null
  value: ''
SAVE_INTERVAL:
  desc: null
  value: 500000.0
BEST_INTERVAL:
  desc: null
  value: 0
GIF_INTERVAL:
  desc: null
  value: 1000000.0
EVAL_INTERVAL:
  desc: null
  value: 16384
EVAL_EPISODES:
  desc: null
  value: 1
RECORD_BEST:
  desc: null
  value: false
MODEL_PATH:
  desc: null
  value: ./models/MAPF/SCRIMP07-03-240057
GIFS_PATH:
  desc: null
  value: ./gifs/MAPF/SCRIMP07-03-240057
SUMMARY_PATH:
  desc: null
  value: ./summaries/MAPF/SCRIMP07-03-240057
TXT_NAME:
  desc: null
  value: alg.txt
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709744408.092825
    t:
      1:
      - 1
      - 30
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      4: 3.7.16
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
